variables:
  versionBase: '2.1.0'
  tool_version: $(versionBase).$(Build.BuildId)

trigger:
  branches:
    include:
     - master 
  paths:
    include:
     - 'src/DacpacToolSolution/*'
     - 'azure-pipelines-dotnet-tool.yml'
     
name: $(versionBase).$(Build.BuildId)

jobs:
  - job: BUILD
    displayName: Generate Nuget package
    pool: 
      vmImage: ubuntu-latest      
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'dotnet pack Dacpac.Tool.csproj /p:Version=$(tool_version) /p:PackageVersion=$(tool_version) -o $(Build.ArtifactStagingDirectory)/artifact'
        workingDirectory: 'src/DacpacToolSolution/Dacpac.Tool'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/artifact'
        ArtifactName: drop
    