variables:
  versionBase: '1.1'
  tool_version: $(versionBase).$(Build.BuildId)

trigger:
  branches:
    include:
     - master 
  paths:
    include:
     - '.netTool/*'
     - 'azure-pipelines-dotnet-tool.yml'
     
name: $(versionBase).$(Build.BuildId)
steps:
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: 'src/DacpacToolSolution/*.csproj'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: 'src/DacpacToolSolution/*.csproj'
    arguments: '/p:Version=$(tool_version) /p:PackageVersion=$(tool_version)'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    packagesToPack: 'src/DacpacToolSolution/*.csproj'
    versioningScheme: 'Off'
    packDirectory: '$(Build.ArtifactStagingDirectory)\artifact'
    buildProperties: 'PackageVersion=$(tool_version)'
    verbosityPack: Normal

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\artifact'
