variables:
  versionBase: '1.1'
  tool_version: $(versionBase).$(Build.BuildId)

trigger:
  branches:
    include:
     - master 
  paths:
    include:
     - 'src/DacpacToolSolution/*'
     - 'azure-pipelines-dotnet-tool.yml'
     
name: $(versionBase).$(Build.BuildId)

jobs:
  - job: BUILD
    displayName: Build and Nuget Push
    pool: 
      vmImage: ubuntu-latest      
    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        workingDirectory: src/DacpacToolSolution/
        arguments: '/p:Version=$(tool_version) /p:PackageVersion=$(tool_version)'
    
    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: pack
        workingDirectory: src/DacpacToolSolution/
        packagesToPack: 'Dacpac.Tool/Dacpac.Tool.csproj'
        versioningScheme: 'Off'
        packDirectory: '$(Build.ArtifactStagingDirectory)\artifact'
        buildProperties: 'PackageVersion=$(tool_version)'
        verbosityPack: Normal
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\artifact'
    